server.port=8080
spring.application.name=order-spring

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=apppass

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:kafka:9094}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

management.endpoints.web.exposure.include=health,info,prometheus

inventory.addr=${INVENTORY_ADDR:inventory-spring:50051}
payment.addr=${PAYMENT_ADDR:payment-spring:50052}
